djangovents/djangovents/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('events.urls')),  # root route to events
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('events/', include('events.urls')),
    # path('', RedirectView.as_view(url='/eventos/', permanent=True))
]

djangovents/events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.EventList.as_view(), name='index'),
    path('events/', views.EventList.as_view(), name='index'),
    path('events/new/', views.NewEvent.as_view(), name='new'),
    path('signup', views.SignUpView.as_view(), name='signup'),
    path('events/<int:pk>', views.EventDetailView.as_view(), name='show'),
    path('events/edit/<int:pk>', views.EventUpdateView.as_view(), name='edit'),
    path('events/delete/<int:pk>', views.EventDeleteView.as_view(), name='delete'),
    path('api/events/', views.EventsApiView.as_view())
]

djangovents/events/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Event(models.Model):
    name = models.CharField('Event name', max_length=60)
    event_date = models.DateField('Event date')
    time_start = models.TimeField('Event start time')
    time_end = models.TimeField('Event end time')
    venue = models.CharField(max_length=120)
    description = models.TextField(max_length=240)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='events')
    date_created = models.DateTimeField(default=timezone.now)
    attendee = models.ManyToManyField(User, related_name='event_attendations', blank=True)

    class Meta:
        indexes = [models.Index(fields=['creator'])]
        verbose_name = 'event'
        verbose_name_plural = 'events'

    def get_absolute_url(self):
        return f"/events/{self.pk}"

    def __str__(self):
        return self.name

djangovents/events/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Event


class SignUpForm(UserCreationForm):
  first_name = forms.CharField(max_length=30, help_text='Required.')
  last_name = forms.CharField(max_length=30, help_text='Required.')
  email = forms.CharField(max_length=254, help_text='Required.')
  class Meta:
    model = User
    fields = [
      'username', 'first_name', 'last_name', 'email'
    ]

class EventForm(ModelForm):
    required_css_class = 'required'
    class Meta:
      model = Event
      exclude = [
        'date_created', 'creator', 'attendee'
        ]

djangovents/events/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import UserCreationForm
from .models import Event
from .forms import EventForm, SignUpForm
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.urls import reverse_lazy
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import serializers
from .serializers import EventSerializer


class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'events/signup.html'


class EventList(ListView):
    model = Event
    template_name = 'events/index.html'

@method_decorator(login_required, name='dispatch')
class NewEvent(CreateView):
    model = Event
    form_class = EventForm
    success_url = 'index'  # if not found, defaults go get_absolute_url
    template_name = 'events/new.html'

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.creator = self.request.user
            self.object.save()
            return redirect(self.get_success_url())

@method_decorator(login_required, name='dispatch')
class EventDetailView(DetailView):
    model = Event
    template_name = "events/show.html"


@method_decorator(login_required, name='dispatch')
class EventDeleteView(DeleteView):
    model = Event
    success_url = reverse_lazy('index')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.creator != self.request.user:
            return redirect(self.success_url)
        return super().post(request, *args, **kwargs)

@method_decorator(login_required, name='dispatch')
class EventUpdateView(UpdateView):
    model = Event
    fields = [
        'name', 'event_date', 'time_start', 
        'time_end', 'venue', 'description']
    template_name = 'events/edit.html'
    success_url = reverse_lazy('index')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.creator != self.request.user:
            return redirect(self.success_url)
        return super().get(request, *args, **kwargs)

## API VIEWS
class EventsApiView(APIView):
    def get(self, request):
        events = Event.objects.all()
        serializer = EventSerializer(events, many=True)
        return Response({'events': serializer.data})

djangovents/djangovents/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django507</title>
</head>
<body>
  <div class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <a href="{% url 'index' %}" class="brand-logo right">Djangovents</a>
        <ul id="nav-mobile" class="left">
          <li><a href="{% url 'index' %}">Events</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'new'%}">New Event</a></li>
            <li><a href="{% url 'logout'%}">Sign out</a></li>
            <li>Welcome, {{ user.first_name }}</li>
          {% else %}
            <li><a href="{% url 'login'%}">Sign in</a></li>
            <li><a href="{% url 'signup'%}">Sign up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </div>
  <div>
    <div class="container">
      <div class="row">
        <div class="col s3"></div>
        <div class="col s6">
          <div class="col s3"></div>
          {% block content %}
          <h3 class="center">Welcome to Djangovents</h3>
          {% endblock content %}
        </div>
      </div>
    </div>
  </div>
</body>
</html>

djangovents/events/templates/events/edit.html
{% extends "base.html" %}

{% block content %}
<h3 class="center">Edit Event</h3>
<form method="POST" novalidate>
  {{ form.as_p }}
  <input type="submit" value="Submit">
{% csrf_token %}
</form>
{% endblock content %}

djangovents/events/templates/events/index.html
{% extends "base.html" %}

{% block content %}
<h3 class="center">All Events</h3>
<table class="striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Date</th>
        <th>Venue</th>
      </tr>
    </thead>
    <tbody>
      {% for event in event_list %}
        <tr>
          <td><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></td>
          <td>{{ event.event_date }}</td>
          <td>{{ event.venue }}</td>
        </tr>
      {% endfor %}
    </tbody>
</table>
{% endblock content %}

djangovents/events/templates/events/new.html
{% extends "base.html" %}

{% block content %}
<h3 class="center">New Event</h3>
<form method="post" novalidate>
  {{ form.as_p }}
  <input type="submit" value="Submit">
{% csrf_token %}
</form>
{% endblock content %}

djangovents/events/templates/events/show.html
{% extends "base.html" %}

{% block content %}
<div class="center">
  <h3>{{ event.name }}</h3>
  {% if user == event.creator %}
    <a href="{% url 'edit' event.id %}">Edit</a>
    <a href="{% url 'delete' event.id %}">Delete</a>
  {% endif %}
</div>
<table class="striped">
  <tr><td class="center">Date: {{ event.event_date }}</td></tr>
  <tr><td class="center">Start at: {{ event.time_start }}</td></tr>
  <tr><td class="center">Ends at: {{ event.time_end }}</td></tr>
  <tr><td class="center">Venue: {{ event.venue }}</td></tr>
  <tr><td class="center">Description: {{ event.description }}</td></tr>
  <tr><td class="center">Created by: {{ event.creator }}</td></tr>
  <tr><td class="center">Published: {{ event.date_created }}</td></tr>
</table>
{% endblock content %}

djangovents/events/templates/events/signup.html
{% extends "base.html" %}
{% block content %}
<h3 class="center">Sign up</h3>
<form method="post" action="{% url 'signup'%}">
  {{ form.as_p }}
  <input type="submit" value="Sign Up">
  <input type="hidden" name="next" value="{{ next }}" />
{% csrf_token %}
</form>
{% endblock content %}